### PR TITLE
Update reasons.ts

### PR DESCRIPTION
**Pull request by Wervice**
I added some more reasons why you shouldn't deploy

### CODE REVIEW

**Comment by baires** [comment]
## Coverage report 


Branches coverage not met for global: expected >=90%, but got 78.125%
| <div title="Status of coverage:&#10; 🟢 - ok&#10; 🟡 - slightly more than threshold&#10; 🔴 - under the threshold">St.<sup>:grey_question:</sup></div> | Category   | Percentage | Covered / Total |
| :----------------------------------------------------------------------------------------------------------------------------------------------------: | :--------- | :--------- | :-------------: |
|                                                                           🟢                                                                           | Statements | 95.08%     |      58/61      |
|                                                                           🟡                                                                           | Branches   | 78.13%     |      25/32      |
|                                                                           🟢                                                                           | Functions  | 95%        |      19/20      |
|                                                                           🟢                                                                           | Lines      | 95%        |      57/60      |


## Test suite run success
24 tests passing in 2 suites.

<p align="right">Report generated by <a href="https://github.com/ArtiomTr/jest-coverage-report-action">🧪jest coverage report action</a> from 43deced9e7832ffa4c89b27e930d1e71ac975e50</p>

**Comment by baires** [comment]
LGTM, feel free to reopen it 🥂

**Comment by Wervice** [comment]
Ok, I'll reopen it.
Alexis Sgarbossa ***@***.***> schrieb am Donnerstag, 18. Januar 2024 um 21:45:

**Comment by Wervice** [comment]
I'm sorry for the discomfort. I reopened the post now, but GitHub said this:
coverage / Coverage-report (pull_request_target)  Failing after 50s
wervice ***@***.***> schrieb am Freitag, 19. Januar 2024 um 11:46 vorm.:

**Comment by baires** [comment]
I think GH token associated with the action is expired, I will take a look tomorrow.
LGTM

**Review by baires — APPROVED** [review]

**Pull request merged**
