### PR TITLE
feat: migrate Head and Timezone to typescript

### PR DESCRIPTION
**Pull request by dennissiq**
## Proposed Changes
- improve types in `footer.tsx`
- change `head.js` to `head.tsx`
- migrate `timezone.tsx` and change class component to function component
- improve `.tsconfig`
- #826 
- #825

### CODE REVIEW

**Comment by dennissiq** [comment]
☝🏻 @baires My deployment has failed, but I can't access Vercel to identify the problem, can u help me?

**Comment by baires** [comment]
its seems a linter issue

```
[11:11:34.334] Failed to compile.
[11:11:34.334] 
[11:11:34.334] ./pages/index.js
[11:11:34.334] 66:33  Error: Insert `⏎············`  prettier/prettier
[11:11:34.335] 67:1  Error: Delete `··`  prettier/prettier
```

**Comment by baires** [comment]
#### 📝 Changed routes:


| [**/**](https://shouldideploy-89gm1qrno-sgavel.vercel.app/) |
|:-:|
|<a href="https://shouldideploy-89gm1qrno-sgavel.vercel.app/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/9v2aTXyce_J9JCGwEnR7Uxn0dZsgCmDmCgd12c9GRbtBbFLEMGCjpZ0KW9B9XwTyw_iAK8j42Z5c-lQ--Sxbvw.png">(view full size)</a> |







Commit 350ea03a86830651609529bf8b4cabf37b4c0b92 (https://shouldideploy-89gm1qrno-sgavel.vercel.app).

**Comment by dennissiq** [comment]
> ####  Changed routes:
> [**/**](https://shouldideploy-89gm1qrno-sgavel.vercel.app/)
> [Screenshot of /](https://shouldideploy-89gm1qrno-sgavel.vercel.app/)
> [(view full size)](https://images.weserv.nl?url=https://sjc.microlink.io/9v2aTXyce_J9JCGwEnR7Uxn0dZsgCmDmCgd12c9GRbtBbFLEMGCjpZ0KW9B9XwTyw_iAK8j42Z5c-lQ--Sxbvw.png)
> Commit [350ea03](https://github.com/baires/shouldideploy/commit/350ea03a86830651609529bf8b4cabf37b4c0b92) (https://shouldideploy-89gm1qrno-sgavel.vercel.app).

This route is generated automatically by Vercel, correct?

**Comment by baires** [comment]
Yes vercel will generate that route
LGTM

**Review by baires — APPROVED** [review]

**Pull request merged**
