### PR TITLE
Feature/add api

### PR DESCRIPTION
**Pull request by baires**
WIP

### CODE REVIEW

**Comment by poocart** [comment]
When this can be merged? 🚀

**Comment by mehdicopter** [comment]
That would be great to have an API :)

**Comment by poocart** [comment]
I got it working with couple of changes added here, will create PR later 👍

Though the problem with that this is linked to Netlify deployment and it's serverless functions can be reached using full path – https://vigilant-boyd-355aac.netlify.com/.netlify/functions/server/api. Maybe anyone has an idea how to redirect them to more human readable urls? Netlify redirect config seems not working explicitly for functions.

**Comment by mehdicopter** [comment]
I wanted an API in order to make a widget for Smashing and display it to our dashboard at work ;)

**Comment by baires** [comment]
@poocart found the same problem at that time. I decided to not spend more time around serverless func on Netlify. I will migrate the project to Zeit (now)

@mehdicopter After migrating to Zeit it would be pretty easy to add and /api

**Comment by baires** [comment]
Addressed on #195

**Pull request closed without merging**
